# Generated by Django 3.1.3 on 2020-11-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semillero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('linea_investigacion', models.CharField(max_length=70)),
                ('anio_constitucion', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=100)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'verbose_name': 'Semillero',
                'verbose_name_plural': 'Semilleros',
                'ordering': ['id'],
            },
        ),
    ]
