# Generated by Django 3.1.3 on 2020-11-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('tipo_publicacion', models.CharField(choices=[('arituclo', 'Articulo'), ('Documentos ', 'Docuemtos de Trabajo'), ('software', 'Softwares'), ('consultorias', 'Consultorías científico-tecnológicas'), ('eventos', 'Eventos Científicos'), ('informes', 'Informes de investigación'), ('contenidovirtual', 'Generación de Contenido Virtual'), ('cti', 'Participación Ciudadana en Proyectos de CTI'), ('ondas', 'Asesorías al Programa Ondas'), ('tutorial', 'Trabajos dirigidos/turorías'), ('jurados', 'Jurado/Comisiones evaluadoras de trabajo de grado'), ('proyectos', 'Proyectos')], default='articulo', max_length=30)),
                ('autores', models.CharField(max_length=255)),
                ('anio_publicacion', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['id'],
            },
        ),
    ]
