# Generated by Django 3.1.3 on 2020-11-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_publicacion',
            field=models.CharField(choices=[('Articulo', 'Articulo'), ('Docuemtos de Trabajo ', 'Docuemtos de Trabajo'), ('software', 'Softwares'), ('consultorias', 'Consultorías científico-tecnológicas'), ('eventos', 'Eventos Científicos'), ('informes', 'Informes de investigación'), ('contenidovirtual', 'Generación de Contenido Virtual'), ('cti', 'Participación Ciudadana en Proyectos de CTI'), ('ondas', 'Asesorías al Programa Ondas'), ('tutorial', 'Trabajos dirigidos/turorías'), ('jurados', 'Jurado/Comisiones evaluadoras de trabajo de grado'), ('proyectos', 'Proyectos')], default='articulo', max_length=30),
        ),
    ]
